name: run-test
description: Run Robot test(s) in common_lib/tests
inputs:
  test_dir:
    description: The working directory that contains the tests
    required: false
    default: "tests"
  robot_env:
    description: The conda environment
    required: false
    default: "~/miniforge3/envs/conda_env_v1.0"
  output_folder:
    description: The folder to place XML results into (under the test_dir).
    required: false
    default: "output"
  xray:
    description: Upload test results to Xray. This is a string value of True or False.
    required: false
    default: "True"
  rack_config:
    description: The rack configuration file name with the entire path.
    required: true
  test_list:
    description: |
      Test file or folder to run in common_lib/tests.
      This can be a single test or a list of tests delimited by a space or comma.
    required: true
runs:
  using: composite
  steps:
    - run: |
        IFS=', ' read -ra TEST <<< "${{ inputs.test_list }}"
        for i in "${TEST[@]}"; do
          $BASE_CMD -o $i.xml common_lib/tests/$i
        done
      env:
        BASE_CMD: >
          conda run -p ${{ inputs.robot_env }} python -m robot 
          -v rack_config:${{ inputs.rack_config }}
          -v allow_xray_upload:${{ inputs.xray }}
          -L DEBUG:DEBUG
          --nostatusrc --exitonerror --settag=robot:continue-on-failure
          --listener common_lib/libraries/xray_listener.py
          -r NONE -l NONE -d ${{ inputs.output_folder }}
      shell: bash -euo pipefail {0}
      working-directory: ${{ inputs.test_dir }}
