name: program
description: Program boards with matching names
inputs:
  test_dir:
    description: The working directory that contains the tests
    required: false
    default: "canvas_mp_tests"
  robot_env:
    description: The conda environment
    required: false
    default: "~/miniforge3/envs/conda_env_v1.0"
  output_folder:
    description: The folder to place XML results into (under the test_dir).
    required: false
    default: "output"
  xray:
    description: |
      Upload test results to Xray. 
      This is a string value of True or False.
      Set to False when programming non-DUT boards.
    required: false
    default: "True"
  station_config:
    description: The station file name with the entire path.
    required: true
  release_version:
    description: |
      A string that represents the release version that will be compared to
      what is read from the board.
    required: true
  board_name:
    description: The [partial] name of the board to program
    required: true
  file_name:
    description: The file name with entire path to program onto the board(s).
    required: true
runs:
  using: composite
  steps:
    - run: >
        conda run -p ${{inputs.robot_env}} python -m robot
        -v station_config:${{inputs.station_config}}
        -v file_name:${{inputs.file_name}}
        -v release_version:${{inputs.release_version}}
        -v board_name:${{inputs.board_name}}
        -v allow_xray_upload:${{inputs.xray}}
        -L DEBUG:DEBUG
        --listener common_lib/libraries/xray_listener.py
        -r NONE -l NONE -d ${{inputs.output_folder}} -o program.xml
        common_lib/tests/firmware_update/00_program.robot
      shell: bash -euo pipefail {0}
      working-directory: ${{inputs.test_dir}}
